/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    views: [
        'MyViewport',
        'ProdRegWindow',
        'FeatureRequestWindow'
    ],
    appFolder: '/../app',
    controllers: [
        'ProdRegController'
    ],
    name: 'iFrame',

    launch: function() {
        Ext.create('iFrame.view.MyViewport');
        iFrame.prodRegW = Ext.create('iFrame.view.ProdRegWindow', {renderTo: Ext.getBody()});
        iFrame.featureW = Ext.create('iFrame.view.FeatureRequestWindow', {renderTo: Ext.getBody()});
        iFrame.request_url = "/softnas/snserver/snserv.php";
    }

});
