/*
 * File: ../app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('iFrame.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'iFrame.view.MyViewportViewModel',
        'Ext.form.Panel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'myviewport'
    },
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            height: 389,
            width: 498,
            bodyPadding: 10,
            title: 'My Form',
            items: [
                {
                    xtype: 'button',
                    margin: 10,
                    padding: '5 15',
                    text: 'Product Registration',
                    listeners: {
                        click: 'onButtonClick'
                    }
                },
                {
                    xtype: 'button',
                    margin: 10,
                    padding: '5 15',
                    text: 'Feature Request',
                    listeners: {
                        click: 'onButtonClick1'
                    }
                }
            ]
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        //Ext.create('iFrame.view.ProdRegWindow', {renderTo: Ext.getBody()});
        iFrame.prodRegW.show();
    },

    onButtonClick1: function(button, e, eOpts) {
        //Ext.create('iFrame.view.FeatureRequestWindow', {renderTo: Ext.getBody()});
        iFrame.featureW.show();
    }

});