/*
 * File: app/store/IniFileStore.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.IniFileStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.IniFileModel',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'IniFileStore',
            autoLoad: false,
            model: 'MyApp.model.IniFileModel',
            proxy: {
                type: 'rest',
                url: '/softnas/snserver/snserv.php?opcode=readini',
                reader: {
                    type: 'json',
                    rootProperty: 'records'
                }
            },
            listeners: {
                load: {
                    fn: me.onJsonstoreLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreLoad: function(store, records, successful, operation, eOpts) {
        var show_welcome = "1";
        if(records.length && records[0].data !== undefined && records[0].data.ini !== undefined && records[0].data.ini.gettingstarted !== undefined &&
           records[0].data.ini.gettingstarted.showWelcomeOnStartup !== undefined){
            show_welcome = records[0].data.ini.gettingstarted.showWelcomeOnStartup;
        }

        Ext.ComponentQuery.query('#checkShowWelcomeOnStartup')[0].setValue( (show_welcome == "1") ? true : false );
        window['ini_loaded'] = true;
    }

});